import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";

const FEATURES = [
  {
    title: "Ask it anything from your notes",
    copy:
      "Type a question the way you'd ask a classmate. The assistant searches your uploaded PDF, pulls the exact passage that answers it, and tells you plainly when your notes don't cover something — instead of guessing.",
  },
  {
    title: "Compress 50 pages into one",
    copy:
      "Pick short, medium, bullet-point, or exam-notes style. Get a revision sheet built from what you actually uploaded, in the time it takes to read this sentence.",
  },
  {
    title: "Flashcards you didn't have to write",
    copy:
      "Front-and-back cards pulled straight from your chapter, ready to flip through between classes.",
  },
  {
    title: "Quiz yourself before the exam does",
    copy:
      "Multiple choice, true/false, and short answer — generated from your notes, scored as you go, so you find the gaps before your professor does.",
  },
];

export default function Home() {
  return (
    <>
      <Helmet>
        <title>AI Study Assistant — Turn Your Notes Into Answers, Summaries & Quizzes</title>
        <meta
          name="description"
          content="Upload your lecture notes or PDFs and get instant answers, exam-ready summaries, flashcards, and quizzes — all generated by AI, grounded only in your own material."
        />
      </Helmet>

      <main>
        {/* Hero */}
        <section className="mx-auto max-w-4xl px-6 pb-16 pt-20 text-center">
          <p className="mb-4 text-sm font-medium uppercase tracking-widest text-ink-400">
            For students who'd rather understand than re-read
          </p>
          <h1 className="font-display text-4xl font-semibold leading-tight text-ink-900 sm:text-5xl">
            Upload your notes. <span className="highlight-mark">Ask real questions.</span> Get answers you can trust.
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg text-ink-600">
            No searching through 200 pages at midnight. Upload a PDF, and get answers, summaries,
            flashcards, and quizzes pulled straight from your own material — nothing invented,
            nothing generic.
          </p>
          <div className="mt-10 flex items-center justify-center gap-4">
            <Link
              to="/register"
              className="rounded-full bg-highlight px-8 py-3 font-medium text-ink-900 transition hover:brightness-95"
            >
              Sign up free
            </Link>
            <Link to="/login" className="text-sm font-medium text-ink-900 underline">
              Already have an account? Log in
            </Link>
          </div>
        </section>

        {/* Features */}
        <section className="mx-auto max-w-6xl px-6 py-16">
          <h2 className="mb-10 text-center font-display text-3xl font-semibold text-ink-900">
            Everything you'd do the night before an exam — done in minutes
          </h2>
          <div className="grid gap-8 sm:grid-cols-2">
            {FEATURES.map((f) => (
              <article
                key={f.title}
                className="rounded-2xl border border-ink-100 bg-white/70 p-6 transition hover:border-highlight"
              >
                <h3 className="font-display text-xl font-semibold text-ink-900">{f.title}</h3>
                <p className="mt-2 text-ink-600">{f.copy}</p>
              </article>
            ))}
          </div>
        </section>

        {/* Trust / how it works */}
        <section className="mx-auto max-w-4xl px-6 py-16 text-center">
          <h2 className="font-display text-2xl font-semibold text-ink-900">
            Grounded in your notes. Nothing else.
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-ink-600">
            If your notes don't cover something, the assistant says so instead of making it up.
            That's the whole point of building this on your own material instead of the open
            internet.
          </p>
        </section>
      </main>
    </>
  );
}
